## Flights
### Data Analysis of Flights.csv

In [2]:
import numpy as np
import pandas as pd

#### Create a DataFrame from CSV data

In [3]:
df = pd.read_csv('data/flights.csv')
df

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2014,1,1,1.0,96.0,235.0,70.0,AS,N508AS,145,PDX,ANC,194.0,1542,0.0,1.0
1,2014,1,1,4.0,-6.0,738.0,-23.0,US,N195UW,1830,SEA,CLT,252.0,2279,0.0,4.0
2,2014,1,1,8.0,13.0,548.0,-4.0,UA,N37422,1609,PDX,IAH,201.0,1825,0.0,8.0
3,2014,1,1,28.0,-2.0,800.0,-23.0,US,N547UW,466,PDX,CLT,251.0,2282,0.0,28.0
4,2014,1,1,34.0,44.0,325.0,43.0,AS,N762AS,121,SEA,ANC,201.0,1448,0.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162044,2014,9,30,2357.0,-2.0,545.0,-20.0,UA,N477UA,479,PDX,IAH,210.0,1825,23.0,57.0
162045,2014,9,30,2359.0,4.0,734.0,-1.0,DL,N137DL,1929,SEA,ATL,244.0,2182,23.0,59.0
162046,2014,9,30,NaN,NaN,NaN,NaN,AS,N530AS,470,SEA,SAN,NaN,1050,NaN,NaN
162047,2014,9,30,NaN,NaN,NaN,NaN,US,NaN,494,PDX,PHX,NaN,1009,NaN,NaN
162048,2014,9,30,NaN,NaN,NaN,NaN,WN,N790SW,427,SEA,SMF,NaN,605,NaN,NaN

#### Describe

In [4]:
df.describe()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,flight,air_time,distance,hour,minute
count,162049.0,162049.000000,162049.000000,161192.000000,161192.000000,161061.000000,160748.000000,162049.000000,160748.000000,162049.000000,161192.000000,161192.000000
mean,2014.0,6.605027,15.749890,1278.283755,6.133859,1482.501282,2.240868,1357.356725,152.588511,1204.514634,12.479515,30.332244
std,0.0,3.324399,8.789417,522.583793,29.112035,523.958781,31.191037,1495.271031,72.547469,653.150062,5.232476,18.061569
min,2014.0,1.000000,1.000000,1.000000,-37.000000,1.000000,-67.000000,2.000000,18.000000,93.000000,0.000000,0.000000
25%,2014.0,4.000000,8.000000,831.000000,-5.000000,1127.000000,-12.000000,408.000000,103.000000,689.000000,8.000000,14.000000
50%,2014.0,7.000000,16.000000,1217.000000,-2.000000,1517.000000,-4.000000,694.000000,129.000000,991.000000,12.000000,30.000000
75%,2014.0,9.000000,23.000000,1721.000000,5.000000,1918.000000,7.000000,1726.000000,199.000000,1660.000000,17.000000,47.000000
max,2014.0,12.000000,31.000000,2400.000000,1553.000000,2400.000000,1539.000000,6527.000000,422.000000,2724.000000,24.000000,59.000000

#### List the data types of each columns

In [5]:
df.dtypes

year           int64
month          int64
day            int64
dep_time     float64
dep_delay    float64
arr_time     float64
arr_delay    float64
carrier       object
tailnum       object
flight         int64
origin        object
dest          object
air_time     float64
distance       int64
hour         float64
minute       float64
dtype: object

#### List all Columns

In [5]:
df.columns

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

#### Size of the data

In [6]:
df.size

2592784

#### Mean flight time

In [8]:
df_by_carrier = df.groupby('carrier')
df_by_carrier['air_time'].mean()

carrier
AA    207.152529
AS    157.214491
B6    203.803035
DL    185.083248
F9    127.906448
HA    336.411172
OO     87.940494
UA    173.493618
US    184.082709
VX    108.918249
WN    120.353820
Name: air_time, dtype: float64

#### Group by US Carrier

In [17]:
df_US = df[df['carrier'] == 'US']
df_US

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
1,2014,1,1,4.0,-6.0,738.0,-23.0,US,N195UW,1830,SEA,CLT,252.0,2279,0.0,4.0
3,2014,1,1,28.0,-2.0,800.0,-23.0,US,N547UW,466,PDX,CLT,251.0,2282,0.0,28.0
11,2014,1,1,549.0,24.0,907.0,12.0,US,N548UW,649,PDX,PHX,122.0,1009,5.0,49.0
47,2014,1,1,650.0,90.0,1037.0,91.0,US,N626AW,460,SEA,PHX,141.0,1107,6.0,50.0
99,2014,1,1,830.0,0.0,1206.0,-12.0,US,N667AW,440,SEA,PHX,132.0,1107,8.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161806,2014,9,30,1118.0,-7.0,1344.0,-12.0,US,N650AW,476,PDX,PHX,126.0,1009,11.0,18.0
161808,2014,9,30,1121.0,1.0,1351.0,-18.0,US,N653AW,614,SEA,PHX,130.0,1107,11.0,21.0
161902,2014,9,30,1448.0,-2.0,1718.0,-18.0,US,N640AW,500,SEA,PHX,131.0,1107,14.0,48.0
162025,2014,9,30,2209.0,-1.0,607.0,9.0,US,N199UW,624,SEA,CLT,280.0,2279,22.0,9.0
162047,2014,9,30,NaN,NaN,NaN,NaN,US,NaN,494,PDX,PHX,NaN,1009,NaN,NaN

#### Group by AS Carrier

In [19]:
df_AS = df[df['carrier'] == 'AS']
df_AS

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2014,1,1,1.0,96.0,235.0,70.0,AS,N508AS,145,PDX,ANC,194.0,1542,0.0,1.0
4,2014,1,1,34.0,44.0,325.0,43.0,AS,N762AS,121,SEA,ANC,201.0,1448,0.0,34.0
14,2014,1,1,557.0,-3.0,825.0,-25.0,AS,N562AS,81,SEA,ANC,188.0,1448,5.0,57.0
15,2014,1,1,558.0,-2.0,801.0,-2.0,AS,N402AS,200,SEA,SJC,100.0,697,5.0,58.0
18,2014,1,1,600.0,-10.0,842.0,-8.0,AS,N786AS,426,SEA,LAX,125.0,954,6.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162035,2014,9,30,2303.0,-7.0,200.0,0.0,AS,N618AS,127,SEA,FAI,215.0,1533,23.0,3.0
162037,2014,9,30,2320.0,20.0,10.0,16.0,AS,N713AS,698,SEA,GEG,36.0,224,23.0,20.0
162042,2014,9,30,2347.0,-3.0,229.0,-2.0,AS,N763AS,121,SEA,ANC,209.0,1448,23.0,47.0
162043,2014,9,30,2349.0,-1.0,514.0,-19.0,AS,N409AS,660,SEA,DFW,188.0,1660,23.0,49.0
162046,2014,9,30,NaN,NaN,NaN,NaN,AS,N530AS,470,SEA,SAN,NaN,1050,NaN,NaN

#### Number of flight records

In [10]:
df['flight'].count()

np.int64(162049)

#### min, mean, and max delays for departure and arrival

In [12]:
df[['dep_delay','arr_delay', 'distance']].agg(['min','mean','max'])

        dep_delay    arr_delay     distance
min    -37.000000   -67.000000    93.000000
mean     6.133859     2.240868  1204.514634
max   1553.000000  1539.000000  2724.000000

#### Number of unique airlines

In [14]:
grouped_by_carrier = df.groupby('carrier')
len(grouped_by_carrier)

11

#### Number of unique aircrafts represented (Tail Number)

In [15]:
grouped_by_tailnum = df.groupby('tailnum')
print(len(grouped_by_tailnum))

# OR

print(df['tailnum'].nunique())
# OR

print(df.tailnum.nunique())

3022
3022
3022

#### Minimum departure delay for your chosen airlines (or all)

In [78]:
grouped_by_carrier = df.groupby('carrier')
grouped_by_carrier['dep_delay'].min()

carrier
AA   -18.0
AS   -25.0
B6   -20.0
DL   -19.0
F9   -20.0
HA   -17.0
OO   -37.0
UA   -19.0
US   -26.0
VX   -21.0
WN   -11.0
Name: dep_delay, dtype: float64

#### Mean departure delay for your chosen airlines (or all)

In [69]:
grouped_by_carrier['dep_delay'].mean()

carrier
AA    10.597632
AS     2.783932
B6     8.462857
DL     4.820384
F9    10.152473
HA     2.580439
OO     4.435644
UA     9.795162
US     2.734850
VX     7.852158
WN    13.329137
Name: dep_delay, dtype: float64

#### Greatest recorded delay

In [71]:
grouped_by_carrier['dep_delay'].max()

carrier
AA    1553.0
AS     866.0
B6     365.0
DL     886.0
F9     815.0
HA     878.0
OO     677.0
UA     580.0
US     711.0
VX     358.0
WN     712.0
Name: dep_delay, dtype: float64

#### Mean delay for the first 50 records

In [74]:
first_50_records = df.head(50)
first_50_records

grouped_by_carrier = first_50_records.groupby('carrier')
grouped_by_carrier['dep_delay'].mean()

carrier
AA    -1.666667
AS     4.000000
DL    17.500000
F9    -2.000000
OO    -6.000000
UA    21.250000
US    26.500000
VX    -6.000000
WN     0.500000
Name: dep_delay, dtype: float64