# Working with External Files. Also Group and Aggregate Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Free datasets website - https://www.kaggle.com/datasets

# we may load external files from Excel, csv, json etc.
df = pd.read_csv('data/salaries.csv') # also Excel, json, xml etc.
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [3]:
df.columns
df.size # total number of data points
df.sum()
df.max() # or min(), count() etc.
df['phd']
df.sex
# df['rank'] # careful - rank is a keyword

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
73    Female
74    Female
75    Female
76    Female
77    Female
Name: sex, Length: 78, dtype: object

In [4]:
# Grouping Data
df_rank = df.groupby(['rank'])
df_rank # we have a group object
df_rank.count()

           discipline  phd  service  sex  salary
rank
AssocProf          13   13       13   13      13
AsstProf           19   19       19   19      19
Prof               46   46       46   46      46

In [5]:
df_n = df.groupby(['salary','sex']) # careful - the data may be extensive
df_n.max()

                    rank discipline  phd  service
salary sex
57800  Male         Prof          A   51       51
62884  Female  AssocProf          A   25       22
63100  Female   AsstProf          A    7        6
71065  Female  AssocProf          B   12        9
72500  Female   AsstProf          A    3        1
...                  ...        ...  ...      ...
155750 Male         Prof          B   22       21
155865 Male         Prof          A   45       43
161101 Female       Prof          B   24       15
162200 Male         Prof          B   35       33
186960 Male         Prof          B   56       49

[75 rows x 4 columns]

In [6]:
# find the mean salary and service for each rank
l = ['salary', 'service']
gb = df.groupby('rank')
gb[l].mean()

                  salary    service
rank
AssocProf   91786.230769  11.307692
AsstProf    81362.789474   2.210526
Prof       123624.804348  21.413043

In [9]:
# mini-challenge
# show the mean salary fpr each rank by male/female
# find mean salary where salary exceeds 120000

# Solution
a = df.groupby(['rank', 'sex'])
a[['salary']].mean()

                         salary
rank      sex
AssocProf Female   88512.800000
          Male    102697.666667
AsstProf  Female   78049.909091
          Male     85918.000000
Prof      Female  121967.611111
          Male    124690.142857

# Aggregate Data

In [12]:
df.agg({'rank' : ['nunique']})  # number of unique occurrances
df.agg({'sex' : ['nunique']})   # number of unique occurrances

         sex
nunique    2

In [16]:
df[['phd', 'salary']]
df[['phd', 'salary']].agg(['min', 'max', 'mean'])

            phd         salary
min    1.000000   57800.000000
max   56.000000  186960.000000
mean  19.705128  108023.782051

In [18]:
# This code and the above code are same.

stats=['min', 'max', 'mean']
which = ['phd', 'salary']

i = df[which]
r = i.agg(stats)
r

            phd         salary
min    1.000000   57800.000000
max   56.000000  186960.000000
mean  19.705128  108023.782051